name: Deploy Cloud Function with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure GCP Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Verify GCP Authentication
      run: gcloud auth list

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Show Terraform plan
      run: terraform plan -input=false
      continue-on-error: true

    - name: Plan Terraform changes
      run: terraform plan -input=false -out=tfplan
      
    - name: Show Terraform plan file
      run: terraform show -json tfplan | jq '.'
      if: success()

    - name: Apply Terraform changes
      run: terraform apply -auto-approve tfplan
      if: success()
